name: Deployment Exercise 1
on:
  pull_request:
    types: opened
  workflow_dispatch:
  push:
jobs:
    test:
      runs-on: 	${{matrix.os}}
      strategy:
        matrix:
          os: [ubuntu-latest]
          node: [16]
      steps:
            - name: Get Code
              uses: actions/checkout@v5
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with: 
                node-version: ${{matrix.node}}
            - name: Cache Dependency
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: npm-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependncies
              run: npm install
            - name: Run Test
              run: npm test
    build:
      runs-on: 	${{matrix.os}}
      strategy:
        matrix:
          os: [ubuntu-latest]
          node: [16]
      steps:
            - name: Get Code
              uses: actions/checkout@v5
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with: 
                node-version: ${{matrix.node}}
            - name: Cache Dependency
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: npm-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependncies
              run: npm install
            - name: Build code
              run: npm run build
    deploy:
        runs-on: 	${{matrix.os}}
        strategy:
          matrix:
            os: [ubuntu-latest]
            node: [16]
        steps:
            - name: Get Code
              uses: actions/checkout@v5
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with: 
                node-version: ${{matrix.node}}
            - name: Cache Dependency
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: npm-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependncies
              run: npm install
            - name: Deploy code
              run: echo "Deloyed!"